apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secrets-sa-keycloak-multiregion
spec:
  refreshInterval: 30
  secretStoreRef:
    kind: ClusterSecretStore
    name: superawesome
  target:
    creationPolicy: Owner
    name: external-secrets-sa-keycloak-multiregion
  data:
  - remoteRef:
      key: superawesome/kws/staging/sa-keycloak-multiregion/KEYSTORE_PASSWORD
      property: KEYSTORE_PASSWORD
      version: "1"
    secretKey: sa-keycloak-multiregion-KEYSTORE_PASSWORD-1
  - remoteRef:
      key: superawesome/kws/staging/sa-keycloak-multiregion/KEYSTORE_KEY_PASSWORD
      property: KEYSTORE_KEY_PASSWORD
      version: "1"
    secretKey: sa-keycloak-multiregion-KEYSTORE_KEY_PASSWORD-1
  - remoteRef:
      key: superawesome/kws/staging/sa-keycloak-multiregion/TRUSTSTORE_PASSWORD
      property: TRUSTSTORE_PASSWORD
      version: "1"
    secretKey: sa-keycloak-multiregion-TRUSTSTORE_PASSWORD-1
  - remoteRef:
      key: superawesome/kws/staging/sa-keycloak-multiregion/INFINISPAN_USER
      property: INFINISPAN_USER
      version: "1"
    secretKey: sa-keycloak-multiregion-INFINISPAN_USER-1
  - remoteRef:
      key: superawesome/kws/staging/sa-keycloak-multiregion/INFINISPAN_PASSWORD
      property: INFINISPAN_PASSWORD
      version: "1"
    secretKey: sa-keycloak-multiregion-INFINISPAN_PASSWORD-1
  refreshInterval: 15s