apiVersion: v1
kind: Secret
metadata:
  name: sa-keycloak-multireg-infinispan-generated-secret
  labels:
    app: infinispan-secret-identities
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  keystore.jks: {{ .Values.infinispan.keystore }}
  truststore.jks: {{ .Values.infinispan.truststore }}
  users.properties: |-
    {{ .Values.infinispan.usersproperties | nindent 4 }}
  groups.properties: |-
    {{ .Values.infinispan.groupsproperties | nindent 4 }}