slack: on-call
pagerduty: Core_Services
team: CoreServices

monitors:

  Keycloak - [{{environment.name}}] - Average Response Duration too high:
    sendAlerts: false
    query: avg(last_5m):sum:keycloak.keycloak_request_duration.sum{*} by {availability-zone,environment} / sum:keycloak.keycloak_request_duration.count{*} by {availability-zone,environment} * 100 > 1500
    affected: Keycloak is used by AA Dashboard / ad-api, Studio, KVI and others
    rootCauses: Either keycloak, the DB or pods have an issue - needs investigation
    possibleConsequences: Auth is too slow or down, users are not able to login or it takes too long, services have slow or failing requests
    runbookURL: https://rukkaz.atlassian.net/wiki/spaces/CLOUD/pages/1438386144/Keycloak+Monitor+-+Average+Response+Duration+too+high
    recommendations: Also see https://app.datadoghq.com/dashboard/9ai-eni-8bn/cloud-account-timeboard
    thresholds:
      critical: 1500
      warning: 800

  Keycloak - [{{environment.name}}] - Too Many Response Errors (over Requests):
    sendAlerts: false
    query: avg(last_5m):sum:keycloak.keycloak_response_errors{*} by {availability-zone,environment} / sum:keycloak.wildfly_undertow_request_count_total{*} by {availability-zone,environment} > 0.1
    affected: Keycloak is used by AA Dashboard / ad-api, Studio, KVI and others
    rootCauses: Either keycloak, the DB or pods have an issue - needs investigation
    possibleConsequences: Auth is down, users are not able to login, services have failing requests
    runbookURL: https://rukkaz.atlassian.net/wiki/spaces/CLOUD/pages/4414112314/Keycloak+Monitor+-+Too+Many+Response+Errors
    recommendations: Also see https://app.datadoghq.com/dashboard/9ai-eni-8bn/cloud-account-timeboard
    thresholds:
      critical: 0.1
      warning: 0.05

  Keycloak - [{{environment.name}}] - Too Many Failed Logins Attempts:
    sendAlerts: false
    query: sum(last_5m):sum:keycloak.keycloak_failed_login_attempts{*} by {environment} > 100
    affected: Keycloak is used by AA Dashboard / ad-api, Studio, KVI and others
    rootCauses: Either we have too many new users with lost password, or we're under brute force attack!
    possibleConsequences:
    runbookURL: https://confluence.superawesome.tv/pages/viewpage.action?pageId=12623949
    recommendations: Also see https://app.datadoghq.com/dashboard/9ai-eni-8bn/cloud-account-timeboard
    thresholds:
      critical: 100
      warning: 60
