apiVersion: v2
name: sa-keycloak-multiregion
description: sa-keycloak with federation plugin
version: 1.2.2
appVersion: 12.0.4

dependencies:
- name: keycloak
  version: 11.0.1
  repository: 'https://codecentric.github.io/helm-charts'

- name: oauth2-proxy
  version: 3.2.5
  repository: https://charts.helm.sh/stable
  condition: oauth2-proxy.enabled

- name: infinispan
  version: 0.2.1
  # repository: 'file://./charts/infinispan/'
  alias: infinispan
